services:
  whisperx-api:
    build: .
    container_name: whisperx-api
    environment:
      HF_TOKEN: ${HF_TOKEN}
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]